---
- name: Install Tailscale VPN on Debian Bookworm
  hosts: all
  become: true

  tasks:
    - name: Add Tailscale GPG key
      ansible.builtin.get_url:
        url: https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg
        dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
        mode: '0644'

    - name: Add Tailscale apt repository
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/tailscale.list
        content: |
          deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/debian bookworm main
        mode: '0644'

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Tailscale
      ansible.builtin.apt:
        name: tailscale
        state: present
