---
- name: Install aptitude
  apt:
    name: aptitude
    update_cache: yes
    cache_valid_time: 3600

- name: Disable default RaspberryPi user
  user:
    name: pi
    state: absent
  when: ansible_machine == "armv7l"

- name: Install man pages db
  apt:
    name: man-db

- name: install various sysadmin utilities
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - dstat
      - strace
      - tmux
- name: install backup tools
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - restic
